# Generated by Django 3.2.9 on 2021-12-02 15:02

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=255, verbose_name='Sarlovha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlovha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlovha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlovha')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, size=[888, 390], upload_to='news/images/%Y/%m', verbose_name='Rasm')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Asosiy qism')),
                ('body_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Asosiy qism')),
                ('body_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Asosiy qism')),
                ('body_en', ckeditor.fields.RichTextField(null=True, verbose_name='Asosiy qism')),
                ('posted_date', models.DateTimeField(verbose_name='Post qilingan vaqt')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ('-posted_date',),
            },
        ),
    ]
