# Generated by Django 3.2 on 2021-12-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=250, verbose_name='Nomi')),
                ('video', models.FileField(null=True, upload_to='video-materials/%Y%m', verbose_name='Video')),
                ('seen', models.PositiveIntegerField(default=0, verbose_name="Ko'rganlar soni")),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Video Material',
                'verbose_name_plural': 'Video Materiallar',
            },
        ),
    ]
