# Generated by Django 3.2 on 2021-12-05 09:35

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_videomaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Asosiy qism')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, size=[888, 390], upload_to='materials/images/%Y/%m', verbose_name='Rasm')),
                ('downloaded', models.PositiveIntegerField(default=0, verbose_name="Ko'chirib olganlar soni")),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
