# Generated by Django 3.2.9 on 2021-12-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='materials/%Y/%m'),
        ),
    ]
