# Generated by Django 3.2.9 on 2021-12-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_materials_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiallar'},
        ),
    ]
