# Generated by Django 3.2.9 on 2021-12-02 15:02

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=300, verbose_name='Nomi')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='Nomi')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Nomi')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Nomi')),
                ('link', models.CharField(max_length=500, null=True, unique=True, verbose_name='Link')),
                ('order', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Tartibi')),
                ('is_static', models.BooleanField(blank=True, default=False, verbose_name='Statik sahifa')),
                ('footer', models.BooleanField(default=False, verbose_name='Pastki menyu')),
                ('is_right', models.BooleanField(default=False, verbose_name="Header o'ng tarafga")),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('name', models.CharField(max_length=64, verbose_name='Nomi')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, size=[500, 500], upload_to='partner/images/%Y/%m', verbose_name='Rasm')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Websayt')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('vkontakte', models.URLField(blank=True, null=True)),
                ('okru', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('rss', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Quyidagi formatda kiritishingiz kerak: '+999999999'. 15 raqamgacha ruxsat etiladi", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon raqam')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='Manzil')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('text_uz', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('additional_link', models.URLField(blank=True, null=True, verbose_name="qo'shimcha manzil")),
            ],
            options={
                'verbose_name': 'Sayt Sozlamalari',
                'verbose_name_plural': 'Sayt Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=256, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Sarlavha')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Matn')),
                ('text_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Matn')),
                ('text_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Matn')),
                ('text_en', ckeditor.fields.RichTextField(null=True, verbose_name='Matn')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('active', models.BooleanField(default=False, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(verbose_name='Tartibi')),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Slayderlar',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('vkontakte', models.URLField(blank=True, null=True)),
                ('okru', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('rss', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoqlar',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
            },
        ),
    ]
