# Generated by Django 3.2.9 on 2021-12-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20211204_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='url',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='additional_link',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='okru',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='rss',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='vkontakte',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='youtube',
        ),
    ]
