# Generated by Django 3.2.9 on 2021-12-04 08:07

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20211204_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='address',
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slag'),
        ),
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Websayt'),
        ),
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartibi'),
        ),
        migrations.AddField(
            model_name='settings',
            name='additional_link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="qo'shimcha link"),
        ),
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='slider',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, size=[1440, 680], upload_to='slider/images/%Y/%m', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.CharField(max_length=512, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Nomi'),
        ),
    ]
