# Generated by Django 3.2.9 on 2021-12-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20211204_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='is_activa',
            new_name='is_active',
        ),
    ]
