# Generated by Django 3.2.9 on 2021-12-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20211204_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='aphorism_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Aforizm'),
        ),
        migrations.AddField(
            model_name='settings',
            name='aphorism_ru',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Aforizm'),
        ),
        migrations.AddField(
            model_name='settings',
            name='aphorism_uz',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Aforizm'),
        ),
    ]
