# Generated by Django 3.2.9 on 2021-12-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_socialnetwork_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
