# Generated by Django 3.2.9 on 2021-12-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_settings_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_right',
            field=models.BooleanField(default=False, verbose_name="O'ngdami"),
        ),
    ]
