# Generated by Django 3.2.9 on 2021-12-09 05:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_settings_our_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='our_mission_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bizning maqsad'),
        ),
        migrations.AddField(
            model_name='settings',
            name='our_mission_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bizning maqsad'),
        ),
        migrations.AddField(
            model_name='settings',
            name='our_mission_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bizning maqsad'),
        ),
    ]
