# Generated by Django 3.2 on 2021-12-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerforevent',
            name='user',
        ),
    ]
