# Generated by Django 3.2 on 2021-12-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_volunteerforevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
