# Generated by Django 3.2 on 2021-12-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Finished'), (3, 'Bekorqilingan')], default=1, null=True, verbose_name='Xolati'),
        ),
    ]
