# Generated by Django 3.2 on 2021-12-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_volunteerforevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_liked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
