# Generated by Django 3.2.9 on 2021-12-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_volunteerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name="Ta'rif"),
        ),
        migrations.AddField(
            model_name='user',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Ta'rif"),
        ),
        migrations.AddField(
            model_name='user',
            name='about_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Ta'rif"),
        ),
    ]
