# Generated by Django 3.2.9 on 2021-12-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20211203_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_networks',
        ),
    ]
