# Generated by Django 3.2.9 on 2021-12-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_remove_userprofile_social_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name="O'zimgiz haqingizda"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="Ma'lumoti"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.TextField(blank=True, null=True, verbose_name='Maqsadi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Qiziqishalar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Til'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Mutaxassisligi'),
        ),
    ]
