# Generated by Django 3.2.9 on 2021-12-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='okru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rss',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vkontakte',
        ),
        migrations.RemoveField(
            model_name='user',
            name='youtube',
        ),
    ]
