# Generated by Django 3.2.9 on 2021-12-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_auto_20211204_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=256, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=256, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Maqsad',
                'verbose_name_plural': 'Maqsadlar',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Til',
                'verbose_name_plural': 'Tillar',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name="O'zingiz haqingizda"),
        ),
    ]
