# Generated by Django 3.2.9 on 2021-12-05 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_auto_20211205_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.PositiveIntegerField(choices=[(1, "O'rta"), (2, "O'rta maxsus"), (3, 'Bakalavr'), (4, 'Magistr')], default=1, verbose_name="Ma'lumoti"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='volunteer.goal', verbose_name='Maqsad'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='volunteer.language', verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Mutaxassisligi'),
        ),
    ]
