# Generated by Django 3.2.9 on 2021-12-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_auto_20211205_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
    ]
