# Generated by Django 3.2.9 on 2021-12-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0011_auto_20211205_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
