# Generated by Django 3.2.9 on 2021-12-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0012_user_youtube'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volunteerrating',
            unique_together={('volunteer', 'organization')},
        ),
    ]
