# Generated by Django 3.2.9 on 2021-12-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0015_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailcode',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
